<Workspace Version="1.1.0.2094" X="-323.72" Y="113.22" zoom="1.1575" Name="Active View" Description="Gets active view or sheet" ID="aab0ca85-2ecb-4464-96be-f64c2f3d1f5d" Category="CM.Sheet">
  <NamespaceResolutionMap>
    <ClassMap partialName="Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="13d85827-0650-4026-84b8-10cc702338da" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="86.5403963044171" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitNodes
clr.AddReference("RevitNodes")
import Revit

# Import Revit elements
from Revit.Elements import *

# Import DocumentManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

import System

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
uidoc = uiapp.ActiveUIDocument
app = uiapp.Application
view = uidoc.ActiveView 

OUT = view</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="68942707-4aa9-49a8-a54e-33fa970ce98c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="550.946004319654" y="208.88120950324" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Active_View_or_Sheet" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="13d85827-0650-4026-84b8-10cc702338da" start_index="0" end="68942707-4aa9-49a8-a54e-33fa970ce98c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>